import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./layout/Header";

const satoshi = localFont({
	src: [
		{
			path: "../public/fonts/Satoshi-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Satoshi-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/Satoshi-Bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-satoshi",
	display: "swap",
});

const titleFont = localFont({
	src: "../public/fonts/MonumentExtended-Regular.woff2",
	variable: "--font-title",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${satoshi.variable} ${titleFont.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
